controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
#Création de mes routes et des controleurs associés
accueil:
  path: /accueil
  controller: App\Controller\HomeController::index

contract_list:
    path: /utilisateurs
    controller: App\Controller\UtilisateurListController::listUtilisateurs

api_profil:
    path: /api/profil
    controller: 'App\Controller\Api\ProfilController::getProfil'
    methods: ['GET']

chiffre_affaire_index:
    path: /chiffre_affaire
    controller: App\Controller\ChiffreAffaireController::index

chiffre_affaire_departement_index:
    path: /chiffre_affaire_departement
    controller: App\Controller\ChiffreAffaireDepartementController::index

login:
    path: /api/login
    controller: App\Controller\AuthController::login
    methods: [POST]    

inscription_succes:
    path: '/inscription/success' # Le chemin de ma route pour le message "inscription réusssie"
    controller: 'App\Controller\UtilisateurController::inscriptionSucces' # Le contrôleur et l'action associés à cette route
